version: '3.7'
services:
  gomemcache-client:
    environment:
      - UPTRACE_DSN
    build:
      dockerfile: $PWD/Dockerfile
      context: ../..
    command:
      - '/bin/sh'
      - '-c'
      - '/go/bin/client'
    networks:
      - example
    depends_on:
      - memcached-server
  memcached-server:
    image: memcached:1.6.6-alpine
    networks:
      - example
networks:
  example:
